name: Publish Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate fallback changelog if needed
        run: |
          # Fallback für das Changelog, falls das Plugin nicht funktioniert
          if ! pip list | grep -q "mkdocs-changelog-plugin"; then
            echo "# Changelog" > docs/changelog.md
            echo "" >> docs/changelog.md
            echo "## Änderungshistorie" >> docs/changelog.md
            echo "" >> docs/changelog.md
            git log --pretty=format:"### %ad - %an%n%s%n%n" --date=short >> docs/changelog.md
          fi
          
      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
